<?php

return [
    'services' => [
        'web development' => 'web_development',
        'web dev' => 'web_development',
        'website development' => 'web_development',
        'digital marketing' => 'digital_marketing',
        'seo' => 'seo',
        'search engine optimization' => 'seo',
        'social media' => 'social_media',
        'ppc' => 'ppc',
        'pay per click' => 'ppc',
        'content marketing' => 'content_marketing',
        'email marketing' => 'email_marketing',
    ],

    'niches' => [
        'restaurant' => 'restaurants',
        'restaurants' => 'restaurants',
        'clinic' => 'clinics',
        'clinics' => 'clinics',
        'real estate' => 'real_estate',
        'realtor' => 'real_estate',
        'agency' => 'agencies',
        'agencies' => 'agencies',
        'retail' => 'retail',
        'hospitality' => 'hospitality',
        'healthcare' => 'healthcare',
        'legal' => 'legal',
        'law firm' => 'legal',
        'small business' => 'small_business',
        'small businesses' => 'small_business',
    ],

    'company_sizes' => [
        'small business' => 'small',
        'small businesses' => 'small',
        'smb' => 'small',
        'sme' => 'small',
        'medium' => 'medium',
        'enterprise' => 'enterprise',
        'startup' => 'startup',
        'startups' => 'startup',
    ],

    'opportunity_signals' => [
        'outdated website' => 'outdated_website',
        'outdated site' => 'outdated_website',
        'weak seo' => 'weak_seo',
        'poor seo' => 'weak_seo',
        'no website' => 'no_website',
        'weak social' => 'weak_social_presence',
        'weak social media' => 'weak_social_presence',
        'poor mobile' => 'poor_mobile_ux',
        'no ssl' => 'no_ssl',
        'needing seo' => 'weak_seo',
        'needing web' => 'web_opportunity',
        'weak online presence' => 'weak_online_presence',
        'incomplete online' => 'weak_online_presence',
    ],

    'cities' => [
        'dubai', 'london', 'new york', 'toronto', 'sydney', 'singapore',
        'los angeles', 'chicago', 'miami', 'vancouver', 'melbourne', 'berlin',
        'paris', 'amsterdam', 'tokyo', 'hong kong', 'mumbai', 'dublin',
    ],

    'countries' => [
        'uae' => 'United Arab Emirates',
        'dubai' => 'United Arab Emirates',
        'uk' => 'United Kingdom',
        'united kingdom' => 'United Kingdom',
        'usa' => 'United States',
        'us' => 'United States',
        'united states' => 'United States',
        'canada' => 'Canada',
        'australia' => 'Australia',
        'germany' => 'Germany',
        'france' => 'France',
        'india' => 'India',
        'ireland' => 'Ireland',
        'netherlands' => 'Netherlands',
        'japan' => 'Japan',
        'singapore' => 'Singapore',
    ],

    'city_to_country' => [
        'dubai' => 'United Arab Emirates',
        'london' => 'United Kingdom',
        'new york' => 'United States',
        'toronto' => 'Canada',
        'sydney' => 'Australia',
        'singapore' => 'Singapore',
        'vancouver' => 'Canada',
        'melbourne' => 'Australia',
        'berlin' => 'Germany',
        'paris' => 'France',
        'amsterdam' => 'Netherlands',
        'tokyo' => 'Japan',
        'hong kong' => 'Hong Kong',
        'mumbai' => 'India',
        'dublin' => 'Ireland',
    ],
];
